import { useContext, useEffect } from "react";
import Head from "next/head";
import ProductCard from "../components/product-card";
import { ProductsContext } from "../store/productsContext";
import productsList from "../data/products.json";

export default function Home() {
  const productsCtx = useContext(ProductsContext);
  const { products, storeProducts } = productsCtx;

  useEffect(() => {
    storeProducts(productsList.slice(0, 12));
  }, []);

  return (
    <>
      <Head>
        <title>Nextjs-Storefront | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="grid gap-6 [grid-template-columns:repeat(auto-fit,minmax(14rem,1fr))]">
        {products.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </section>
    </>
  );
}
