import Head from "next/head";
import ProductCard from "../components/product-card";

import products from "../data/products.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs-Rtk-Storefront | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="grid gap-6 [grid-template-columns:repeat(auto-fit,minmax(14rem,1fr))]">
        {/* TODO: remove slice */}
        {products.slice(0, 12).map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </section>
    </>
  );
}
