import Head from "next/head";
import UserProductsList from "../components/user-products-list";

import products from "../data/products.json";

export default function WishList() {
  return (
    <>
      <Head>
        <title>Nextjs-Rtk-Storefront | WishList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h2 className="mb-10 text-center text-3xl font-bold">WishList</h2>
        <UserProductsList isWishList={true} products={products} />
      </section>
    </>
  );
}
